# Generated by Django 4.2.29 on 2026-03-24 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golitep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesgame',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='minesgame',
            name='current_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='minesgame',
            name='winnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
