# Generated by Django 5.0.2 on 2026-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_ou_pile', '0002_rename_player2_choice_faceoupilegame_coin_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceoupilegame',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faceoupilegame',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceoupilegame',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceoupilegame',
            name='round_chooser',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faceoupilegame',
            name='round_results',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
