# Generated by Django 5.0.2 on 2026-08-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_ou_pile', '0003_faceoupilegame_current_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceoupilegame',
            old_name='player1_choice',
            new_name='chooser_choice',
        ),
    ]
