# Generated by Django 4.2.29 on 2026-03-25 08:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoulettePartie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('gagné', 'Gagné'), ('perdu', 'Perdu')], default='en_cours', max_length=10)),
                ('mise', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('numero_pari', models.IntegerField(blank=True, null=True)),
                ('numero_tire', models.IntegerField(blank=True, null=True)),
                ('gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
