"""
Django settings for projet_casino project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t4g&1@lha&=%soyy4!!bk*g^=pdyajx2hod-od4hc^1v=pbjfp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'casino_app.core.apps.CoreConfig',
    'casino_app.wallet.apps.WalletConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    
    
    'casino_app.lucky_numbers.apps.LuckyNumbersConfig',
    'casino_app.golitep.apps.GolitepConfig',
    'casino_app.roulette.apps.RouletteConfig',
    'casino_app.slots.apps.SlotsConfig',
    'casino_app.blackjack.apps.BlackjackConfig',
    'casino_app.poker.apps.PokerConfig',
    'casino_app.baccarat.apps.BaccaratConfig',
    'casino_app.craps.apps.CrapsConfig',
    'casino_app.keno.apps.KenoConfig',
    'casino_app.bingo.apps.BingoConfig',
    'casino_app.sic_bo.apps.SicBoConfig',
    'casino_app.pai_gow.apps.PaiGawConfig',
    'casino_app.fan_tan.apps.FanTanConfig',
    'casino_app.red_dog.apps.RedDogConfig',
    'casino_app.three_card_poker.apps.ThreeCardPokerConfig',
    'casino_app.caribbean_stud_poker.apps.CaribbeanStudPokerConfig',
    'casino_app.let_it_ride.apps.LetItRideConfig',
    'casino_app.casino_war.apps.CasinoWarConfig',
    'casino_app.pontoon.apps.PontoonConfig',
    'casino_app.spanish_21.apps.Spanish21Config',
    'casino_app.double_exposure_blackjack.apps.DoubleExposureBlackjackConfig',
    'casino_app.omaha_poker.apps.OmahaPokerConfig',
    'casino_app.texas_holdem.apps.TexasHoldemConfig',
    'casino_app.video_poker.apps.VideoPokerConfig',
    'casino_app.scratch_cards.apps.ScratchCardsConfig',
    'casino_app.checkers.apps.CheckersConfig',
    'casino_app.ludo.apps.LudoConfig',
    'casino_app.rock_paper_scissors.apps.RockPaperScissorsConfig',
    'casino_app.face_ou_pile.apps.FaceOuPileConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projet_casino.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projet_casino.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# REST framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Désactive WhiteNoise en développement pour éviter les 304 et accélérer le chargement
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Django Channels configuration
ASGI_APPLICATION = 'projet_casino.asgi.application'

# Redis configuration for Channels
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Channel layer configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}