# Generated by Django 5.0.2 on 2026-04-21 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('active', 'En cours'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=10)),
                ('board_state', models.JSONField(default=dict)),
                ('current_turn', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('move_history', models.JSONField(default=list)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkers_games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkers_games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkers_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partie de Dames',
                'verbose_name_plural': 'Parties de Dames',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('locked', 'Bloqué'), ('released', 'Libéré'), ('refunded', 'Remboursé')], default='locked', max_length=10)),
                ('transaction_type', models.CharField(choices=[('escrow', 'Escrow'), ('winnings', 'Gains')], default='escrow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='checkers.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction de jeu',
                'verbose_name_plural': 'Transactions de jeu',
                'ordering': ['-created_at'],
            },
        ),
    ]
