# Generated by Django 4.2.29 on 2026-03-25 13:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('stood', 'Debout'), ('busted', 'Dépassé'), ('won', 'Gagné'), ('lost', 'Perdu'), ('push', 'Égalité')], default='playing', max_length=10)),
                ('player_cards', models.JSONField(default=list)),
                ('dealer_cards', models.JSONField(default=list)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('winnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('player_score', models.IntegerField(default=0)),
                ('dealer_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackjack_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
