# Generated by Django 4.2.29 on 2026-03-26 10:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCardGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
                ('card_type', models.CharField(default='classic', max_length=20)),
                ('symbols', models.JSONField(default=list)),
                ('prize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('winnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='finished', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_card_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
