# Generated by Django 5.0.2 on 2026-05-07 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LudoGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('active', 'En cours'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=10)),
                ('current_turn', models.IntegerField(default=0)),
                ('game_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ludo_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partie LUDO',
                'verbose_name_plural': 'Parties LUDO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LudoGameTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stake', 'Mise'), ('refund', 'Remboursement'), ('win', 'Gain')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ludo.ludogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ludo_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction LUDO',
                'verbose_name_plural': 'Transactions LUDO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LudoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Rouge'), ('blue', 'Bleu'), ('green', 'Vert'), ('yellow', 'Jaune')], max_length=10)),
                ('turn_order', models.IntegerField(default=0)),
                ('is_connected', models.BooleanField(default=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('remaining_time', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ludoplayers', to='ludo.ludogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ludo_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Joueur LUDO',
                'verbose_name_plural': 'Joueurs LUDO',
                'ordering': ['turn_order'],
                'unique_together': {('game', 'user')},
            },
        ),
    ]
