# Generated by Django 5.0.2 on 2026-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ludogame',
            name='min_players',
            field=models.IntegerField(default=2, help_text='Nombre minimum de joueurs requis pour démarrer'),
        ),
    ]
