# Generated by Django 4.2 on 2026-01-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('kibutu', 'Kibutu - Pile ou Face'), ('roulette', 'Roulette'), ('blackjack', 'Blackjack'), ('memory', 'Memory')], max_length=50, unique=True)),
                ('nom_affichage', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mise_min', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('mise_max', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('type_jeu', models.CharField(choices=[('solo', 'Solo'), ('multi', 'Multijoueur')], max_length=10)),
                ('commission', models.IntegerField(default=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='PartieKibutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partie', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('solo', 'Solo'), ('multi', 'Multijoueur')], max_length=10)),
                ('mise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choix_j1', models.CharField(blank=True, choices=[('pile', 'Pile'), ('face', 'Face')], max_length=10)),
                ('choix_j2', models.CharField(blank=True, choices=[('pile', 'Pile'), ('face', 'Face')], max_length=10)),
                ('manche1_resultat', models.CharField(blank=True, choices=[('pile', 'Pile'), ('face', 'Face')], max_length=10)),
                ('manche2_resultat', models.CharField(blank=True, choices=[('pile', 'Pile'), ('face', 'Face')], max_length=10)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commission_totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gains_gagnant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('gagnant_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_kibutu_gagnees', to=settings.AUTH_USER_MODEL)),
                ('manche1_gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manches_gagnees_1', to=settings.AUTH_USER_MODEL)),
                ('manche2_gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manches_gagnees_2', to=settings.AUTH_USER_MODEL)),
                ('utilisateur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_kibutu_j1', to=settings.AUTH_USER_MODEL)),
                ('utilisateur2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_kibutu_j2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partie Kibutu',
                'verbose_name_plural': 'Parties Kibutu',
            },
        ),
        migrations.CreateModel(
            name='TransactionSolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('mise', 'Mise'), ('gain', 'Gain'), ('commission', 'Commission')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('partie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casino_app.partiekibutu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Solde',
                'verbose_name_plural': 'Transactions Solde',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_vip', models.IntegerField(default=0)),
                ('parties_jouees', models.IntegerField(default=0)),
                ('parties_gagnees', models.IntegerField(default=0)),
                ('total_mise', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_gains', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_acces', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
    ]
