# Generated by Django 4.2 on 2026-01-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_app', '0002_delete_jeu_remove_profilutilisateur_utilisateur_and_more'),
    ]

    operations = []
