# Generated by Django 4.2 on 2026-01-14 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casino_app', '0003_delete_jeu_remove_profilutilisateur_utilisateur_and_more'),
    ]

    operations = []
