# Generated by Django 4.2 on 2026-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance (demandée lors du retrait)', null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='first_name',
            field=models.CharField(blank=True, help_text='Prénom (demandé lors du retrait)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], help_text='Sexe (demandé lors du retrait)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nom (demandé lors du retrait)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone utilisé pour la connexion', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='Profil complété pour retrait'),
        ),
    ]
