# Generated by Django 4.2.27 on 2026-01-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_app', '0005_profilutilisateur_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='profile_complete',
        ),
    ]
