# Generated by Django 6.0.3 on 2026-03-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_app', '0006_remove_profilutilisateur_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='nom',
            field=models.CharField(choices=[('kibutu', 'Kibutu - Pile ou Face'), ('roulette', 'Roulette'), ('blackjack', 'Blackjack'), ('memory', 'Memory'), ('aviator', 'Aviator')], max_length=50, unique=True),
        ),
    ]
