# Generated by Django 4.2.29 on 2026-03-26 08:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('won', 'Gagné'), ('lost', 'Perdu')], default='playing', max_length=10)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('winnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('hand', models.JSONField(default=list)),
                ('hold', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
