# Generated by Django 4.2.29 on 2026-03-26 09:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SicBoGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('bet_type', models.CharField(choices=[('small', 'small'), ('big', 'big'), ('odd', 'odd'), ('even', 'even'), ('triple', 'triple'), ('pair', 'pair'), ('single_1', 'single_1'), ('single_2', 'single_2'), ('single_3', 'single_3'), ('single_4', 'single_4'), ('single_5', 'single_5'), ('single_6', 'single_6'), ('total_4', 'total_4'), ('total_5', 'total_5'), ('total_6', 'total_6'), ('total_7', 'total_7'), ('total_8', 'total_8'), ('total_9', 'total_9'), ('total_10', 'total_10'), ('total_11', 'total_11'), ('total_12', 'total_12'), ('total_13', 'total_13'), ('total_14', 'total_14'), ('total_15', 'total_15'), ('total_16', 'total_16'), ('total_17', 'total_17')], default='small', max_length=20)),
                ('dice', models.JSONField(default=list)),
                ('total', models.IntegerField(default=0)),
                ('winnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='finished', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sic_bo_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
